# Generated by Django 2.2.4 on 2019-08-15 15:03

from django.db import migrations, models
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.TextField(default=users.models.generate_id, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('about', models.TextField()),
                ('company', models.TextField(null=True)),
                ('role', models.TextField(null=True)),
                ('responsibilities', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
