# Generated by Django 2.2.4 on 2019-08-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190815_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='company',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='role',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
