version: '3'

services:

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=wolf_and_badger
      - POSTGRES_USER=atsushi
      - POSTGRES_PASSWORD=secretpassword
      - ALLOW_IP_RANGE=0.0.0.0/0

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/profiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
      - selenium
    environment:
      - SECRET_KEY=$SECRET_KEY
      - DOCKER=$Docker

  selenium:
    image: selenium/standalone-chrome-debug:3.7.1
    ports:
      - 4444:4444
      - 5900:5900
